## 26 Feb Assignment- NumPy

### Date:- 26 Feb 2023

In [ ]:
Consider the below code to answer further questions: 

In [11]:
import numpy as np 
list_ = [ "1" , "2" , "3" , "4" , "5" ] 
array_list = np.array(object = list_)  

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code  to print the data types of both the variables. 


## Answer:-

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [7]:
type(list_)

list

In [8]:
type(array_list)

numpy.ndarray

# Q2. Write a code to print the data type of each and every element of both the variables list_ and  arra_list. 


## Answer:-

In [13]:
# print element present in variable list_
for i in list_:
    ty=type(i)
    print(f"type of {i} is :",ty)

type of 1 is : <class 'str'>
type of 2 is : <class 'str'>
type of 3 is : <class 'str'>
type of 4 is : <class 'str'>
type of 5 is : <class 'str'>


In [12]:
# print element present in variable array_list
for i in array_list:
    ty=type(i)
    print(f"type of {i} is:",ty)

type of 1 is: <class 'numpy.str_'>
type of 2 is: <class 'numpy.str_'>
type of 3 is: <class 'numpy.str_'>
type of 4 is: <class 'numpy.str_'>
type of 5 is: <class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list: 
array_list = np.array(object = list_, dtype = int) 

Will there be any difference in the data type of the elements present in both the variables, list_ and  arra_list? If so then print the data types of each and every element present in both the variables, list_  and arra_list.

## Answer:-

In [16]:
import numpy as np 
list_ = [ "1" , "2" , "3" , "4" , "5" ] 
# new array
array_list = np.array(object = list_, dtype = int)

In [17]:
list_

['1', '2', '3', '4', '5']

In [18]:
type(list_)

list

In [19]:
array_list

array([1, 2, 3, 4, 5])

In [20]:
type(array_list)

numpy.ndarray

 Data type of element present in both the variable are changed as shown in output.
 
 Now we will print the elements in both variable:
 

In [21]:
# print element present in variable list_
for i in list_:
    ty=type(i)
    print(f"type of {i} is:",ty)

type of 1 is: <class 'str'>
type of 2 is: <class 'str'>
type of 3 is: <class 'str'>
type of 4 is: <class 'str'>
type of 5 is: <class 'str'>


In [22]:
# print element present in variable array_list
for i in array_list:
    ty=type(i)
    print(f"Type of {i} is :",ty)# datatype of element in output is numpy.int64. previously it was numpy.str

Type of 1 is : <class 'numpy.int64'>
Type of 2 is : <class 'numpy.int64'>
Type of 3 is : <class 'numpy.int64'>
Type of 4 is : <class 'numpy.int64'>
Type of 5 is : <class 'numpy.int64'>



Consider the below code to answer further questions: 

import numpy as np 

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ] 

num_array = np.array(object = num_list) 

# Q4. Write a code to find the following characteristics of variable, num_array: 
## (i)  shape 
## (ii) size 


## Answer:-

In [23]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [24]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [25]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

#### (i) shape

In [26]:
num_array.shape

(2, 3)

#### (ii) size

In [27]:
num_array.size

6

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array  creation function. 
[Hint: The size of the array will be 9 and the shape will be (3,3).] 


## Answer:-

In [38]:
shape_=(3,3)

In [39]:
numpy_array=np.zeros(shape_)

In [40]:
numpy_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
numpy_array.size

9

In [41]:
numpy_array.shape

(3, 3)

# Q6. Create an identity matrix of shape (5,5) using numpy functions? 
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

## Answer:-

In [ ]:
# 1. using diag function

In [51]:
num_mat=np.array([1,1,1,1,1])

In [52]:
num_mat

array([1, 1, 1, 1, 1])

In [53]:
np.diag(num_mat)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# 2. using eye function

In [55]:
num_eye=np.eye(5)

In [56]:
num_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
num_eye.shape

(5, 5)