# Numpy Part 3

In [1]:
import numpy as np

#### Array Manuplulation

In [3]:
arr=np.random.randint(1,10,(4,4))

In [4]:
arr

array([[8, 1, 3, 3],
       [4, 9, 6, 7],
       [8, 2, 4, 5],
       [1, 4, 8, 6]])

In [5]:
arr.reshape(8,2)

array([[8, 1],
       [3, 3],
       [4, 9],
       [6, 7],
       [8, 2],
       [4, 5],
       [1, 4],
       [8, 6]])

In [8]:
arr

array([[8, 1, 3, 3],
       [4, 9, 6, 7],
       [8, 2, 4, 5],
       [1, 4, 8, 6]])

In [9]:
arr.T

array([[8, 4, 8, 1],
       [1, 9, 2, 4],
       [3, 6, 4, 8],
       [3, 7, 5, 6]])

In [10]:
arr.flatten()

array([8, 1, 3, 3, 4, 9, 6, 7, 8, 2, 4, 5, 1, 4, 8, 6])

In [11]:
np.expand_dims(arr)

TypeError: _expand_dims_dispatcher() missing 1 required positional argument: 'axis'

In [12]:
np.expand_dims(arr,axis=1)

array([[[8, 1, 3, 3]],

       [[4, 9, 6, 7]],

       [[8, 2, 4, 5]],

       [[1, 4, 8, 6]]])

In [13]:
np.expand_dims(arr,axis=0) # convert 2 dimensional to 3 dimensional at any point of time.

array([[[8, 1, 3, 3],
        [4, 9, 6, 7],
        [8, 2, 4, 5],
        [1, 4, 8, 6]]])

In [14]:
data=np.array([[1],[2],[3]]) 

In [15]:
data

array([[1],
       [2],
       [3]])

In [16]:
np.squeeze(data) #convert 2 dimensional to 1 dimensional at any point of time.

array([1, 2, 3])

In [17]:
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [18]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [20]:
np.roll(data,2)  # 0th position value add 2 and position of value changed.

array([[2],
       [3],
       [1]])

In [21]:
np.diag(np.array([1,2,3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### Binary operation

In [22]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [23]:
arr1

array([[3, 9, 5, 5],
       [9, 9, 3, 1],
       [8, 5, 8, 7]])

In [24]:
arr2

array([[9, 6, 9, 2],
       [1, 8, 1, 2],
       [3, 7, 8, 8]])

In [25]:
arr1+arr2

array([[12, 15, 14,  7],
       [10, 17,  4,  3],
       [11, 12, 16, 15]])

In [26]:
~arr1

array([[ -4, -10,  -6,  -6],
       [-10, -10,  -4,  -2],
       [ -9,  -6,  -9,  -8]])

### String operation

In [27]:
arr2=np.array(["nitesh","kumar","srivastava"])

In [28]:
arr2

array(['nitesh', 'kumar', 'srivastava'], dtype='<U10')

In [29]:
# convert the string data into uppercase
np.char.upper(arr2)

array(['NITESH', 'KUMAR', 'SRIVASTAVA'], dtype='<U10')

In [31]:
# convert the string data into capitalize
np.char.capitalize(arr2)

array(['Nitesh', 'Kumar', 'Srivastava'], dtype='<U10')

In [32]:
np.char.title(arr2)

array(['Nitesh', 'Kumar', 'Srivastava'], dtype='<U10')

### Numpy Mathematical operation

In [33]:
arr1

array([[3, 9, 5, 5],
       [9, 9, 3, 1],
       [8, 5, 8, 7]])

In [34]:
np.sin(arr1)

array([[ 0.14112001,  0.41211849, -0.95892427, -0.95892427],
       [ 0.41211849,  0.41211849,  0.14112001,  0.84147098],
       [ 0.98935825, -0.95892427,  0.98935825,  0.6569866 ]])

In [35]:
np.cos(arr1)

array([[-0.9899925 , -0.91113026,  0.28366219,  0.28366219],
       [-0.91113026, -0.91113026, -0.9899925 ,  0.54030231],
       [-0.14550003,  0.28366219, -0.14550003,  0.75390225]])

In [36]:
np.power(arr1,2)

array([[ 9, 81, 25, 25],
       [81, 81,  9,  1],
       [64, 25, 64, 49]])

In [48]:
np.median(arr1)

6.0

In [49]:
np.mod(arr1)

TypeError: remainder() takes from 2 to 3 positional arguments but 1 were given

### Arithmetic operation

In [38]:
arr1

array([[3, 9, 5, 5],
       [9, 9, 3, 1],
       [8, 5, 8, 7]])

In [40]:
arr3=np.random.randint(1,10,(3,4))

In [41]:
arr3

array([[5, 9, 4, 2],
       [6, 9, 3, 5],
       [8, 6, 1, 8]])

In [42]:
arr1-arr3

array([[-2,  0,  1,  3],
       [ 3,  0,  0, -4],
       [ 0, -1,  7, -1]])

In [43]:
# numpy method
np.subtract(arr1,arr3)

array([[-2,  0,  1,  3],
       [ 3,  0,  0, -4],
       [ 0, -1,  7, -1]])

In [54]:
np.mod(arr1,arr3)

array([[3, 0, 1, 1],
       [3, 0, 0, 1],
       [0, 5, 0, 7]])