# Numpy Part 1

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [4]:
arr=np.array(l)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
# another way
np.asarray(l)

array([1, 2, 3, 4, 5])

In [9]:
arr1=np.array([[1,2,3],[4,5,6]]) # 2 brackets means 2 dimension in nature

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr1.ndim

2

In [12]:
arr.ndim

1

In [16]:
mat=np.matrix(l) # array can 1 dimensional but matrix always have a 2 dimensional.

In [17]:
mat

matrix([[1, 2, 3, 4, 5]])

In [19]:
np.asanyarray(l) # l is a list so it will convert in array

array([1, 2, 3, 4, 5])

In [20]:
np.asanyarray(mat) # matrix is a subclass of array inside a Numpy so result will be as it is.

matrix([[1, 2, 3, 4, 5]])

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
a=arr

In [23]:
a

array([1, 2, 3, 4, 5])

In [24]:
arr[2]=45

In [25]:
arr

array([ 1,  2, 45,  4,  5])

In [26]:
a # this kind of operation is a solo copy operation

array([ 1,  2, 45,  4,  5])

In [27]:
b=np.copy(arr)

In [28]:
b

array([ 1,  2, 45,  4,  5])

In [29]:
b[0]=236

In [30]:
b

array([236,   2,  45,   4,   5])

In [31]:
arr # not changed in data becuase b work as a reference in another memory

array([ 1,  2, 45,  4,  5])

In [32]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j:i==j,(2,3))

array([[ True, False, False],
       [False,  True, False]])

In [34]:
np.fromfunction(lambda i,j:i*j,(2,3))

array([[0., 0., 0.],
       [0., 1., 2.]])

In [35]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [36]:
iterable=(i*i for i in range(5))

In [38]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [41]:
np.fromstring("23 45 56",sep=" ",dtype=int)

array([23, 45, 56])

In [44]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.fromstring("23,45,56",sep=",",dtype=int)

array([23, 45, 56])

In [45]:
arr

array([ 1,  2, 45,  4,  5])

In [46]:
arr.size

5

In [47]:
arr1.size

6

In [48]:
arr.shape

(5,)

In [49]:
arr1.shape

(2, 3)

In [50]:
arr.dtype

dtype('int64')

In [51]:
arr1.dtype

dtype('int64')