# Numpy Part 4

### Short, Search and counting function

In [1]:
import numpy as np

# sort

In [34]:
arr=np.array([2,3,5,8,4])

In [35]:
arr

array([2, 3, 5, 8, 4])

In [36]:
np.sort(arr) # output sort in ascending order

array([2, 3, 4, 5, 8])

In [37]:
# sort in descending order
np.sort(arr)[::-1]

array([8, 5, 4, 3, 2])

# search

In [46]:
arr

array([2, 3, 5, 8, 4])

In [50]:
arr1=np.sort(arr)

In [51]:
arr1

array([2, 3, 4, 5, 8])

In [52]:
# Find index to maintain sorting order

np.searchsorted(arr1,6)

# The line np.searchsorted(arr1, 6) uses the searchsorted() function to find the index where the
# value 6 should be inserted into arr1 to maintain its sorted order. This function takes 
# two arguments: the array to search in (arr1), and the value to search for (6).

4

# count

In [53]:
arr2=np.array([3,4,7,0,2,0,4,0,8,0,3,4,0])

In [54]:
np.count_nonzero(arr2)

8

In [55]:
np.where(arr2>0) # give indexes where data greater than 0

(array([ 0,  1,  2,  4,  6,  8, 10, 11]),)

In [60]:
np.extract(arr2>0,arr2) # give value of index position

array([3, 4, 7, 2, 4, 8, 3, 4])

In [58]:
np.extract(arr2>3,arr2)

array([4, 7, 4, 8, 4])

###  Byte swapping

In [61]:
arr2

array([3, 4, 7, 0, 2, 0, 4, 0, 8, 0, 3, 4, 0])

In [62]:
arr2.byteswap(inplace=True)

array([216172782113783808, 288230376151711744, 504403158265495552,
                        0, 144115188075855872,                  0,
       288230376151711744,                  0, 576460752303423488,
                        0, 216172782113783808, 288230376151711744,
                        0])

In [63]:
arr2

array([216172782113783808, 288230376151711744, 504403158265495552,
                        0, 144115188075855872,                  0,
       288230376151711744,                  0, 576460752303423488,
                        0, 216172782113783808, 288230376151711744,
                        0])

### copy and views

In [64]:
arr1

array([2, 3, 4, 5, 8])

In [65]:
a=np.copy(arr1)

In [66]:
a

array([2, 3, 4, 5, 8])

In [67]:
b=arr1.view() # shallow copy

# In Shallow copy, a copy of the original object is stored and only the reference address is finallycopied. 
# In Deep copy, the copy of the original object and the repetitive copies both are stored.

In [68]:
b

array([2, 3, 4, 5, 8])

In [69]:
b[1]=45

In [70]:
b

array([ 2, 45,  4,  5,  8])

In [71]:
arr1

array([ 2, 45,  4,  5,  8])

### matrix library

In [72]:
import numpy.matlib as nm

In [73]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [75]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [76]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

### linear algebra

In [79]:
arr3=np.random.randint([[2,3],[4,5]])

In [80]:
arr3

array([[0, 1],
       [2, 3]])

In [83]:
arr4=np.random.randint([[5,3],[2,5]])

In [84]:
arr4

array([[2, 0],
       [0, 3]])

In [85]:
# dot product
np.dot(arr3,arr4)

array([[0, 3],
       [4, 9]])

In [87]:
# Another method of dot product
arr3 @ arr4

array([[0, 3],
       [4, 9]])