# Numpy Part 2

In [1]:
import numpy as np

In [2]:
range(5) #range function only consider the integer 

range(0, 5)

In [4]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0.4,10.4)) # #range function only consider the integer 

TypeError: 'float' object cannot be interpreted as an integer

In [8]:
np.arange(0.4,10.4)  # numpy has a functionality to take float number too in range.

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [9]:
list(np.arange(0.4,10.4)) 

[0.4,
 1.4,
 2.4,
 3.3999999999999995,
 4.3999999999999995,
 5.3999999999999995,
 6.3999999999999995,
 7.3999999999999995,
 8.399999999999999,
 9.399999999999999]

In [11]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [12]:
np.logspace(1,5,20)

array([1.00000000e+01, 1.62377674e+01, 2.63665090e+01, 4.28133240e+01,
       6.95192796e+01, 1.12883789e+02, 1.83298071e+02, 2.97635144e+02,
       4.83293024e+02, 7.84759970e+02, 1.27427499e+03, 2.06913808e+03,
       3.35981829e+03, 5.45559478e+03, 8.85866790e+03, 1.43844989e+04,
       2.33572147e+04, 3.79269019e+04, 6.15848211e+04, 1.00000000e+05])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((3,4,2)) # 4 rows and 2 column and total sets are 3

# output will be visualized in 3-D form

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [17]:
np.zeros((3,4,2,3)) # it can generate but not possible to visualized

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
arr=np.ones((3,4))

In [21]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [23]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [27]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [29]:
np.eye(5) # It's a identity matrix and always rows=column and value in diagonal form.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
arr1=np.eye(5)

In [33]:
import pandas as pd
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [34]:
np.random.rand(2,3) # In the rand, mean and std can have any number

array([[0.90182714, 0.39204672, 0.74682738],
       [0.83523778, 0.80952415, 0.5760978 ]])

In [36]:
np.random.randn(2,3) # whereever i need normally distributed data set then randn used. mean=0 std=1

array([[-0.34754106, -1.72410317, -0.27382174],
       [-0.16708187,  1.2801169 , -2.07902464]])

In [40]:
np.random.randint((2,3))

array([1, 2])

In [42]:
arr2=np.random.randint(1,5, (2,3)) # data will generated between 1 to 5

In [43]:
arr2

array([[3, 3, 1],
       [1, 4, 2]])

In [44]:
arr2.size

6

In [45]:
arr2.shape

(2, 3)

In [48]:
arr2.reshape(3,2)

array([[3, 3],
       [1, 1],
       [4, 2]])

In [49]:
arr2.reshape(2,-1) # After 2, it understand automatically 3 and  inplace of -1 
                   # we can write any number in negative form

array([[3, 3, 1],
       [1, 4, 2]])

In [51]:
# create 3D data
arr2.reshape(3,1,2) # After multiplication it should be equal to 6 for (3,2) shape.

array([[[3, 3]],

       [[1, 1]],

       [[4, 2]]])

In [54]:
arr3=np.random.randint(1,10,(5,6))

In [55]:
arr3

array([[3, 1, 2, 5, 5, 3],
       [4, 9, 4, 5, 1, 9],
       [7, 9, 1, 2, 3, 7],
       [2, 6, 4, 5, 1, 8],
       [6, 2, 9, 5, 1, 9]])

In [59]:
arr3>5

array([[False, False, False, False, False, False],
       [False,  True, False, False, False,  True],
       [ True,  True, False, False, False,  True],
       [False,  True, False, False, False,  True],
       [ True, False,  True, False, False,  True]])

In [60]:
arr3[arr3>5]

array([9, 9, 7, 9, 7, 6, 8, 6, 9, 9])

In [61]:
arr3

array([[3, 1, 2, 5, 5, 3],
       [4, 9, 4, 5, 1, 9],
       [7, 9, 1, 2, 3, 7],
       [2, 6, 4, 5, 1, 8],
       [6, 2, 9, 5, 1, 9]])

In [62]:
# I want to filter 3,1
arr3[0]


array([3, 1, 2, 5, 5, 3])

In [63]:
arr3[0,[0,1]]

array([3, 1])

In [72]:
# I want to generate 2,3 and 5,1
arr3[2:4,[3,4]]

array([[2, 3],
       [5, 1]])

In [75]:
arr4=np.random.randint(1,5,(3,3))
arr5=np.random.randint(1,5,(3,3))

In [76]:
arr4

array([[2, 2, 2],
       [1, 2, 2],
       [2, 1, 2]])

In [77]:
arr5

array([[1, 2, 3],
       [3, 2, 3],
       [1, 4, 1]])

In [78]:
arr4+arr5 # index wise adition operation perform

array([[3, 4, 5],
       [4, 4, 5],
       [3, 5, 3]])

In [79]:
arr4*arr5

array([[2, 4, 6],
       [3, 4, 6],
       [2, 4, 2]])

In [82]:
# If I want to matrix operation
arr4@arr5

array([[10, 16, 14],
       [ 9, 14, 11],
       [ 7, 14, 11]])

In [84]:
arr4/arr5

array([[2.        , 1.        , 0.66666667],
       [0.33333333, 1.        , 0.66666667],
       [2.        , 0.25      , 2.        ]])

In [85]:
arr4/0

/tmp/ipykernel_2164/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

### Broadcasting

In [88]:
arr6=np.zeros([3,4])

In [89]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
arr6+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [91]:
a=np.array([1,2,3,4])

In [92]:
a

array([1, 2, 3, 4])

In [93]:
arr6+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [94]:
b=np.array([3,4,5])

In [95]:
b

array([3, 4, 5])

In [96]:
b+arr6

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [97]:
b=np.array([[3,4,5]])

In [98]:
b

array([[3, 4, 5]])

In [101]:
arr6.shape

(3, 4)

In [102]:
b.shape

(1, 3)

In [103]:
b.T # T is Transpose here and it convert the rows into column

array([[3],
       [4],
       [5]])

In [104]:
arr7=arr6+b.T

In [105]:
arr7

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [106]:
np.sqrt(arr7)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [107]:
np.log10(arr7)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [108]:
np.exp(arr7)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [109]:
np.min(arr7)

3.0

In [111]:
np.sum(arr7)

48.0